project_name: "Loop_Gaussian_SLAM_scannet"
dataset_name: "scan_net"
checkpoint_path: null
use_wandb: True
optimize_with_loop_closure: True
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
mapping:
  new_submap_every: 50
  map_every: 5
  iterations: 100
  new_submap_iterations: 100
  new_submap_points_num: 100000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 30000 
  new_points_radius: 0.0001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: False
tracking:
  gt_camera: False
  w_color_loss: 0.6
  iterations: 200
  cam_rot_lr: 0.002
  cam_trans_lr: 0.01
  odometry_type: "const_speed"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "hybrid" # hybrid or point_to_plane
  filter_alpha: True
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: True
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  depth_scale: 1000.
  crop_edge: 12
pose_graph:
  gt_relative_pose: False
  opacity_threshold: 0.95
  odo_matching_threshold: 0.02
  loop_matching_threshold: 0.005
  downsample_number: 500
  odometry_weight: 1.0
  loop_weight: 1.0
  optimization_max_iterations: 500
  optimization_step_size: 0.005
  rel_err_tolerance: 0.0001
  damping: 0.05
  track_best_solution: True
  verbose: True
loop_closure:
  netvlad_checkpoint_path: /home/stud/lxuh/LoopClosure_for_Gaussian_Splatting_SLAM/vgg16_netvlad_checkpoint/checkpoints/checkpoint.pth.tar
  encoder_name: "vgg16"
  k_neighbours: 4