project_name: "Loop_Gaussian_SLAM_replica"
dataset_name: "replica"
checkpoint_path: null
use_wandb: True
optimize_with_loop_closure: False
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
mapping:
  new_submap_every: 50
  map_every: 5
  iterations: 100
  new_submap_iterations: 1000
  new_submap_points_num: 600000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: -1 
  new_points_radius: 0.0000001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.1 
  submap_using_motion_heuristic: True
tracking:
  gt_camera: False
  w_color_loss: 0.95
  iterations: 60
  cam_rot_lr: 0.0002
  cam_trans_lr: 0.002
  odometry_type: "odometer"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "point_to_plane" # hybrid or point_to_plane 
  filter_alpha: False
  filter_outlier_depth: True
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: False
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  depth_scale: 6553.5
pose_graph:
  gt_relative_pose: False
  opacity_threshold: 0.95
  odo_matching_threshold: 0.002
  loop_matching_threshold: 0.001
  downsample_number: 500
  odometry_weight: 1.0
  loop_weight: 2.5
  optimization_max_iterations: 500
  optimization_step_size: 0.002
  rel_err_tolerance: 0.0001
  damping: 0.05
  track_best_solution: True
  verbose: True
loop_closure:
  netvlad_checkpoint_path: /home/stud/lxuh/LoopClosure_for_Gaussian_Splatting_SLAM/vgg16_netvlad_checkpoint/checkpoints/checkpoint.pth.tar
  encoder_name: "vgg16"
  k_neighbours: 4
